In [1]:
import pandas as pd
for i in range(1,20):
    try:
        df = pd.read_csv(f'Data/data{i}.csv')
        print('-'*50)
        print('DATA:',i)
        print('-'*50)
        print(df.isna().sum())
    except:
        pass
    pass

--------------------------------------------------
DATA: 1
--------------------------------------------------
Head             15
Body             15
Tags             16
First Answer    688
dtype: int64
--------------------------------------------------
DATA: 2
--------------------------------------------------
Head              2
Body              2
Tags              3
First Answer    663
dtype: int64
--------------------------------------------------
DATA: 3
--------------------------------------------------
Head             15
Body             15
Tags             16
First Answer    688
dtype: int64
--------------------------------------------------
DATA: 4
--------------------------------------------------
Head              0
Body              0
Tags              1
First Answer    598
dtype: int64
--------------------------------------------------
DATA: 5
--------------------------------------------------
Head              0
Body              0
Tags              0
First Answer    650
dtype: int64
--------------------------------------------------
DATA: 6
--------------------------------------------------
Head              0
Body              0
Tags              0
First Answer    634
dtype: int64
--------------------------------------------------
DATA: 7
--------------------------------------------------
Head              0
Body              0
Tags              1
First Answer    607
dtype: int64
--------------------------------------------------
DATA: 8
--------------------------------------------------
Head              0
Body              0
Tags              3
First Answer    649
dtype: int64
--------------------------------------------------
DATA: 9
--------------------------------------------------
Head              0
Body              0
Tags              0
First Answer    544
dtype: int64
--------------------------------------------------
DATA: 10
--------------------------------------------------
Head             20
Body             20
Tags             20
First Answer    596
dtype: int64
--------------------------------------------------
DATA: 11
--------------------------------------------------
Head              0
Body              0
Tags              0
First Answer    246
dtype: int64
--------------------------------------------------
DATA: 12
--------------------------------------------------
Head               0
Body               0
Tags               0
First Answer    1654
dtype: int64
--------------------------------------------------
DATA: 13
--------------------------------------------------
Head              19
Body              19
Tags              19
First Answer    1658
dtype: int64
--------------------------------------------------
DATA: 15
--------------------------------------------------
Head               1
Body             203
Tags             204
First Answer    2220
dtype: int64
--------------------------------------------------
DATA: 16
--------------------------------------------------
Head               0
Body               0
Tags               5
First Answer    2194
dtype: int64
--------------------------------------------------
DATA: 19
--------------------------------------------------
Head              23
Body              23
Tags              23
First Answer    3878
dtype: int64